stages:
- stage: Build
  jobs:
  - job: BuildPackage
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/build'
        artifact: 'build'
        publishLocation: 'pipeline'
      

- stage: Dev

  jobs:
  - deployment: DeployementDev
    environment: Check
    strategy:
     runOnce:
      deploy:
         steps:
          - task: DownloadPipelineArtifact@2
            inputs:
             buildType: 'current'
             targetPath: '$(Pipeline.Workspace)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure Devops Service'
              appType: 'webAppLinux'
              WebAppName: 'ReactDev'
              packageForLinux: '$(Pipeline.Workspace)/build'


- stage: QA

  jobs:
  - deployment: DeployementQA
    environment: Check
    strategy:
     runOnce:
      deploy:
         steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Pipeline.Workspace)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure Devops Service'
              appType: 'webAppLinux'
              WebAppName: 'ReactDev'
              packageForLinux: '$(Pipeline.Workspace)/build'
     